### ISSUE TITLE
some way to clear drawing area

### ISSUE THREAD

**Issue by Akuli** [Akuli/mathpaste#11]

**Comment by Akuli** [comment]
it's currently possible to clear drawing area by pressing ctrl+z repeatedly with drawing area opened, but that's not ideal

how to fix this:

1. figure out which functions run when ctrl+z is pressed and how to clear drawing area with them
2. add another separator space and another button to where buttons are in drawing area (copy/paste one of the other buttons and modify)
3. make the button run the clearing code when clicked
4. draw rubber icon add it to `pics/` (black foreground, transparent background)
5. in one of the `.ts` files (don't remember which), there's a bunch of `import "pics/foo.png"`, add one for the rubber image
6. do one of the following:
    - add a message box saying "do you really want to clear everything you have drawn? that can't be undone"
    - make the clearing undoable
    - ask me to make the clearing undoable

**Comment by PurpleMyst** [comment]
We can clear `this.objects` to clean the drawing area.

As far as restoring goes, we'd need to introduce a totally different mechanism due to the current undo just popping from `this.objects`, maybe if `this.objects` is empty we could restore from some new attribute called `this.oldObjects`? Or, we would need to introduce an "event log", where clearing is one of the events. At that point we'd probably also need to introduce an event log size limit..

**Comment by PurpleMyst** [comment]
Here's a potential stroke of genius: Replace this.objects with a zipper list of drawing events, where:

- Drawing clears the right part of the zipper and appends a new drawing event (with an object)
- Undoing moves you left in the zipper
- Re-doing moves you right in the zipper
- Clearing all moves everything to the right part of the zipper

We'd just draw everything from the left and current part of the zipper.

What do you think of this design? I can implement it as I'm familiar with zipper lists.

**Comment by Akuli** [comment]
I was thinking of something along the lines of `this.oldObjects`. The only disadvantage is that you can't undo more than two clears, and I don't think it would bother anyone.

**Comment by PurpleMyst** [comment]
I've set up a branch that has the zipper data structure. As you can see, it's very simple and solves exactly our problem. https://github.com/Akuli/mathpaste/commit/0a584b3ee5cefc5e8ed82d73758061fe32473103
What do you think?

**Comment by Akuli** [comment]
We don't need redo, at least not yet, and `this.oldObjects` is a much simpler way to implement clear all

Also, I think trash can icon would be much better than rubber icon

**Comment by PurpleMyst** [comment]
I'm on it. Do you have an icon in mind?

**Comment by Akuli** [comment]
There's now a branch named `akuli-canvas-clear` based on your branch. It uses a mop icon that I drew.

I think my mop icon looks too much like a stick pointing at a blackboard or whiteboard. What do you think?

**Comment by PurpleMyst** [comment]
Yeah it.. doesn't really evoke a mop for me. Maybe we should go back to the trash-can idea?

**Comment by Akuli** [comment]
I downloaded a nice trash can icon, it's now on dev branch

**Comment by PurpleMyst** [comment]
Have you checked its usage rights?

**Comment by Akuli** [comment]
It says "Personal Use". If you think it's not good enough then I can try to draw my own.

**Comment by PurpleMyst** [comment]
Hmm.. this might not qualify as personal use. But I don't think we'll get any lawyers knocking at our door.

**Comment by Akuli** [comment]
Now it uses a trash icon that I drew

**Comment by Akuli** [comment]
fixed
