### ISSUE TITLE
can't write >= to beginning of line

### ISSUE THREAD

**Issue by Akuli** [Akuli/mathpaste#15]

**Comment by Akuli** [comment]
it's not possible to have `>bla` (in the beginning of a line) for markdown and `>bla` for "greater than bla" at the same time, but I think `>=bla` for "greater than or equal to bla" could still be helpful

I wanted to write `>=bla` today and it didn't work

**Comment by PurpleMyst** [comment]
Perhaps we could introduce `\>` to escape the start-of-line markdown behavior?

**Comment by Akuli** [comment]
turns out that `\>` works already (not sure why)

**Comment by PurpleMyst** [comment]
I think it's just because escaping the greater-than sign means nothing to asciidoc but our line processing code sees it as.. well, a line not starting with the markdown trigger character. We should add this to the documentation that #20 is concerned with.

Should we close this?

**Comment by Akuli** [comment]
I think `\>` and `\>=` just need to be documented in #20
