### ISSUE TITLE
can't draw if draw area is opened too soon

### ISSUE THREAD

**Issue by Akuli** [Akuli/mathpaste#19]
steps to reproduce:
1. open mathpaste, open draw area while mathpaste is still loading
2. try to draw something

**Comment by PurpleMyst** [comment]
what was the bug? :o

**Comment by Akuli** [comment]
IIRC `readOnly` was not set to `false` when page finished loading, so this happened:
1. open drawing area (`readOnly = false`)
2. page begins loading (`readOnly = true`)
3. page loading done
4. try to draw and be confused
5. close drawing area (`readOnly = true`)
6. open drawing area (`readOnly = false`)

`readOnly` no longer needs to be set when the drawing area is not showing because of c9d6687 but it's still set to true while loading

after fixing that, `imageData` was dumped on top of freshly drawn stuff, so I changed `imageData` to be used only when drawing something (that's the only time when it's truly needed)
