### ISSUE TITLE
brace's ace version is ancient

### ISSUE THREAD

**Issue by PurpleMyst** [Akuli/mathpaste#3]
As per the title, the ace version that `brace` "browserifies" is ancient. The latest commit is from February 2018, and at the time of writing the date is June 2019. So it's almost a year and a half old.

We could fork `brace` and set up something (github webhook?) that automatically updates an `npm` package every time a new commit of `ace-builds` comes out.

We'll have to toy with this.

**Comment by PurpleMyst** [comment]
Trying to switch to ace-builds itself creates wonky behavior, as can be seen in e4d0bfc188fb9a40e8c813c4b87b40f529245cc9 which caused its revertion in 94694fdc2d0f27aca54eb8c8d65f338732876258

**Comment by PurpleMyst** [comment]
I think this might be related to ajaxorg/ace-builds#17

**Comment by PurpleMyst** [comment]
here's an issue comment that seems to outline the steps necessary to depend on ace-builds instead of brace (which is not updated anymore) 

https://github.com/ajaxorg/ace/issues/4782

maybe we should add some sort of snapshot test in Jest, like the ones you can use to test React apps

**Comment by Akuli** [comment]
reopening because ajaxorg/ace-builds#27 got reverted
