### ISSUE TITLE
feature idea: rubber to drawing area

### ISSUE THREAD

**Issue by Akuli** [Akuli/mathpaste#30]
when the rubber touches a drawn object, the entire object gets deleted, not just a part of it (otherwise rubbering a circle too difficult to implement)

rubbering must be undoable

**Comment by PurpleMyst** [comment]
So, practically, removing an object of choice from `this.objects`?

**Comment by PurpleMyst** [comment]
If we want erasing to be undoable, we must switch to a sort of "event log" like I talked about before. I'm working on this

**Comment by PurpleMyst** [comment]
Hm, I don't think [Path2D](https://developer.mozilla.org/en-US/docs/Web/API/Path2D) includes a way to check if a point intersects the path.

Only workaround I can think of is drawing the path to a fake blank canvas, getting the imagedata and seeing if the point we're clicking on is within some distance from a colored point on the canvas

but that might get expensive fast and it feels hacky

**Comment by Akuli** [comment]
>I don't think Path2D includes a way to check if a point intersects the path

We don't actually want point-path intersection, because then the mouse would need to be **exactly** on the line being deleted, with the precision of one pixel.

Instead I would like to allow off-by-3-pixels or something like that:

```
if (distance(path, mouse) <= 3) {
    delete drawn object;
}
```

The check `distance(path, mouse) <= 3` can be also written as `intersects(circle(mouse, 3), path)`, where `circle(mouse, 3)` is a circle of radius `3` with `mouse` as center.

`Path2D` seems to provide no intersection tests for paths, but fortunately they aren't that hard to implement by hand:
- Circle-circle intersection is easy (but filled and non-filled circles must be treated differently)
- Circle-line intersection is slightly more complicated but still not too bad. A little bit different. Let `AB` denote a vector from `A` to `B`. Circle with center C and line from A to B intersect if and only if any of these conditions are true:
    - `A` intersects circle (aka `distance(A, C) < radius`)
    - `B` intersects circle
    - The distance between `C` and the line passing through `A` and `B` is less than radius, **and** the projection of `AC` onto `AB` is between `0` and `distance(A, B)`

**Comment by Akuli** [comment]
I guess I should also mention that projection of `AC` onto `AB` can be written as `dotProduct(AB, AC) / distance(A, B)`

**Comment by PurpleMyst** [comment]
We'd probably have to have this as a method on the DrawObject interface, right?

```typescript
distance: (point: [number, number]) => number
```

**Comment by Akuli** [comment]
It might be slightly easier to implement `intersectsCircle(center: [number, number], radius: number) -> bool`, because we don't really need a distance calculation. We just need to intersect everything with circles representing a small area around the mouse pointer.

**Comment by Akuli** [comment]
After thinking about this a bit more, a distance calculation wouldn't be too bad either.

To calculate distance between a line from `A` to `B` and a point `C`, we would first project `AC` onto `AB`. If the projection is between `0` and `distance(A, B)`, then use the formula for distance between line and point; otherwise, use the distance to the nearest end point (`A` if the projection is negative, `B` if the projection is greater than `distance(A, B)`).

**Comment by Akuli** [comment]
I think I might want to implement this one

**Comment by Akuli** [comment]
code is on `rubber` branch, some things not done yet:

- [ ] add rubber icon
- [ ] when hovering canvas with rubber selected, show the circle around mouse cursor that will be rubbered

It's a little bit weird that barely touching a draw object deletes the entire object, but it makes implementing this a lot easier. Otherwise rubbering could split a line into two pieces and create **more** draw objects, and that would have to be undoable.

**Comment by PurpleMyst** [comment]
It wouldn't be *too* too hard to support rubbering just a point from a circle/line/pen, but I'm not sure how useful that'd be. Although, semi-circles sound useful. Maybe this could be a different tool?

Also, making it undoable isn't too hard with the event system

**Comment by Akuli** [comment]
done in #33
