### ISSUE TITLE
SimpleCrypto.prototype.decrypt(string, boolean) is deprecated

### ISSUE THREAD

**Issue by PurpleMyst** [Akuli/mathpaste#32]
On [Line 91 of pasteManager.ts](https://github.com/Akuli/mathpaste/blob/93f9912/js/pasteManager.ts#L91) we pass a boolean as the second argument to `SimpleCrypto.prototype.decrypt`.

The JSDoc for this function mentions that such an overload is deprecated, and reading [the source code](https://github.com/danang-id/simple-crypto-js/blob/79f25a6/src/SimpleCrypto.ts#L316-L338) for the function it seems that the argument now does nothing.

I'd just remove it but I'm
1) Not sure how to test that behavior remains the same
2) Not sure what the `true` argument was meant to accomplish

Considering you were the one to write this code, @Akuli, do you remember why we have that boolean?

(P.S.: simple-crypto-js v3 is out, we could look into upgrading to that version perhaps)

**Comment by Akuli** [comment]
That's supposed to pass the decrypted string to `JSON.parse` automatically, so that the result is an object instead of a string of JSON.

**Comment by Akuli** [comment]
Also, you are looking at the wrong overload of `decrypt`. The correct one is `public decrypt(cipher: CipherText, expectsObject: boolean): PlainData`

**Comment by PurpleMyst** [comment]
I don't think it's the wrong overload? As far as I can see, it's the only definition of decrypt() there is, and the boolean argument means nothing there

**Comment by Akuli** [comment]
It seems that the overloads above it are not actually methods, but they just declare the valid ways to call the method you linked, so `expectsObject` indeed does nothing

>1. Not sure how to test that behavior remains the same

Try creating a paste and opening the paste URL. The paste should load without errors on console.
