### ISSUE TITLE
window.location.hash doesn't reset when drawing

### ISSUE THREAD

**Issue by Akuli** [Akuli/mathpaste#6]
after saving a mathpaste, the URL in address bar becomes something like `https://akuli.github.io/mathpaste/#saved:-Lxk8niJxIgyqqaKfZal`

changing something in the editor will change the url to `https://akuli.github.io/mathpaste/#` to let the user know that what they are looking at no longer matches the saved paste

but doing something with the drawing area doesn't change url

**Comment by PurpleMyst** [comment]
Alright so, we basically just never register an on-change handle that resets `window.location.hash`. Once #21 is merged, I will fix this by adding the `changeType` mechanism and the handler.
